version: '3.8'

services:
  backend:
    build:
      context: ./backend/slda-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/slda
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: 123456789
    networks:
      - slda-net

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - slda-net

  db:  # <- This must be inside 'services:'
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: slda
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - slda-net

networks:
  slda-net:

volumes:
  pgdata:
